const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const UPDATE = 'UPDATE'
const CREATE = 'CREATE';
const ADDREPOS = 'ADDREPOS';
const GETALLPOSTS = 'GETALLPOSTS';
const GETFOCUSEDPOST = 'GETFOCUSEDPOST';
const CREATE_TEMPLATE = 'CREATE_TEMPLATE';
const DELETE_TEMPLATE = 'DELETE_TEMPLATE';
const GET_TEMPLATES = 'GET_TEMPLATES'


const types = {
  LOGIN,
  LOGOUT,
  UPDATE,
  CREATE,
  ADDREPOS,
  GETALLPOSTS,
  GETFOCUSEDPOST,
  CREATE_TEMPLATE,
  DELETE_TEMPLATE,
  GET_TEMPLATES
};

export default types;
